 const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

function Layout() {
  return (
    <div>
      <h1>{metadata.title}</h1>
      <p>{metadata.description}</p>
    </div>
  );
}

export default Layout;
